OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStoreMVCUsingLinq;
using OnlineShoppingStoreMVCUsingLinq.BO;
using System.Web.UI.WebControls;

namespace OnlineShoppingStoreMVCUsingLinq.Areas.Admin.Controllers
{
    [Authorize]
    public class SubCategoryController : Controller
    {
        SubCategoryBO objSubCategoryBO = new SubCategoryBO();
        CategoryBO objCartegoryBO = new CategoryBO();

        // GET: /Admin/SubCategory/
        public ActionResult Index()
        {
            ViewBag.CategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            return View(objSubCategoryBO.GetSubCategories());
        }
        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            if (fc["btnSearch"] == "Search" && fc["Category"]!="")
            {
                int categoryId = Convert.ToInt32(fc["Category"]);
                ViewBag.CategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName", categoryId);
                return View(objSubCategoryBO.GetSubCategories(categoryId, true));
            }
            else
            {
                ViewBag.CategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
                return View(objSubCategoryBO.GetSubCategories());
            }
        }
        // GET: /Admin/SubCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subcategory = objSubCategoryBO.GetsubCategory(id.Value);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return View(subcategory);
        }

        // GET: /Admin/SubCategory/Create
        public ActionResult Create()
        {
            ViewBag.FKCategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            return View();
        }

        // POST: /Admin/SubCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubCategory subcategory, HttpPostedFileBase Images, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                subcategory.FKCategoryId = Convert.ToInt32(fc["CategoryName"]);
                string imageName = System.IO.Path.GetFileName(Images.FileName);
                Images.SaveAs(Server.MapPath("~/Images/" + imageName));
                subcategory.ImageName = imageName;
                subcategory.ImagePath = "/Images/" + imageName;
                objSubCategoryBO.InsertSubCategory(subcategory);
                return RedirectToAction("Index");
            }

            ViewBag.FKCategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName", subcategory.FKCategoryId);
            return View(subcategory);
        }

        // GET: /Admin/SubCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subcategory = objSubCategoryBO.GetsubCategory(id.Value);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.FKCategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName", subcategory.FKCategoryId);
            return View(subcategory);
        }

        // POST: /Admin/SubCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubCategory subcategory, HttpPostedFileBase txtFile)
        {
            if (ModelState.IsValid)
            {
                if (txtFile != null)
                {
                    string imageName = System.IO.Path.GetFileName(txtFile.FileName);
                    txtFile.SaveAs(Server.MapPath("~/Images/" + imageName));
                    subcategory.ImageName = imageName;
                    subcategory.ImagePath = "/Images/" + imageName;
                }
                objSubCategoryBO.UpdateSubCategory(subcategory);
                return RedirectToAction("Index");
            }
            ViewBag.FKCategoryId = new SelectList(objCartegoryBO.GetCategories(true), "PKCategoryId", "CategoryName", subcategory.FKCategoryId);
            return View(subcategory);
        }

        // GET: /Admin/SubCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subcategory = objSubCategoryBO.GetsubCategory(id.Value);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return View(subcategory);
        }

        // POST: /Admin/SubCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            objSubCategoryBO.DeleteSubCategory(id);
            return RedirectToAction("Index");
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/SubCategory/Create.cshtml
@model OnlineShoppingStoreMVCUsingLinq.SubCategory

@{
    ViewBag.Title = "Create";
}

<h2>Add SubCategory</h2>

@using (Html.BeginForm("Create", "SubCategory", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Category, "CategoryName", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryName",ViewBag.FKCategoryId as SelectList)
                @Html.ValidationMessageFor(model => model.CategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubCategoryName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubCategoryName)
                @Html.ValidationMessageFor(model => model.SubCategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Images" id="Images" />
                @Html.ValidationMessageFor(model => model.ImagePath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/SubCategory/Delete.cshtml
@model OnlineShoppingStoreMVCUsingLinq.SubCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Subcategory</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserProfile.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedByUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserProfile1.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-Primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/SubCategory/Details.cshtml
@model OnlineShoppingStoreMVCUsingLinq.SubCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SubCategory Details</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserProfile.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedByUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserProfile1.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PKSubCategoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/SubCategory/Edit.cshtml
@model OnlineShoppingStoreMVCUsingLinq.SubCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit SubCategory</h2>

@using (Html.BeginForm("Edit", "SubCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubCategory</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.PKSubCategoryId)
        @Html.HiddenFor(model => model.FKCreatedByUserId)
        @Html.HiddenFor(model => model.FKUpdatedByUserId)
        @Html.HiddenFor(model => model.CreatedDate)
        @Html.HiddenFor(model => model.ImageName)
        @Html.HiddenFor(model => model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.FKCategoryId, "FKCategoryId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FKCategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.FKCategoryId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubCategoryName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubCategoryName)
                @Html.ValidationMessageFor(model => model.SubCategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName)
                @Html.ValidationMessageFor(model => model.ImageName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.ImagePath" alt="loading...." height="150" width="150"/>
                <input type="file" name="txtFile" value="" /> 
                @Html.ValidationMessageFor(model => model.ImagePath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-Primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/SubCategory/Index.cshtml
@model IEnumerable<OnlineShoppingStoreMVCUsingLinq.SubCategory>

@{
    ViewBag.Title = "Index";
}

<h2>SubCategory</h2>

<p>
    @Html.ActionLink("Add SubCategory", "Create")
</p>
@using (Html.BeginForm())
{
    <div>
        @Html.Label("Category")
        @Html.DropDownList("Category", ViewBag.CategoryId as SelectList," Select Category")
        <input type="submit" name="btnSearch" value="Search" class="btn btn-sm btn-primary" />
        <input type="submit" name="btnReset" value="Reset" class="btn btn-sm btn-primary" />
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubCategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedByUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedByUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubCategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedByUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedByUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PKSubCategoryId })
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.PKSubCategoryId })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.PKSubCategoryId })
            </td>
        </tr>
    }

</table>