OnlineShoppingStoreMVCUsingLinq/Controllers/ConfirmController.cs
using OnlineShoppingStoreMVCUsingLinq.BO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStoreMVCUsingLinq.Controllers
{
    [Authorize]
    public class ConfirmController : Controller
    {
        BillingAddressBO objBillingAddressBO = new BillingAddressBO();
        ProductBO objProductBO = new ProductBO();
        Order objOrder = new Order();
        OrderBO objOrderBO = new OrderBO();
        OrderDetail objOrderDetail = new OrderDetail();
        OrderDetailBO objOrderDetailBO = new OrderDetailBO();
        OrderHistory objOrderHistory = new OrderHistory();
        OrderHistoryBO objOrderHistoryBO = new OrderHistoryBO();

        //
        // GET: /Confirm/
        public ActionResult PlaceOrder()
        {
            return View();
        }
        [HttpPost, ActionName("PlaceOrder")]
        public ActionResult ConfirmOrder(BillingAddress objBillingAddress)
        {
            objBillingAddressBO.InsertBillingAddress(objBillingAddress);
            int addressId = objBillingAddress.PKAddressId;
            HttpCookie CartCookie = Request.Cookies[Helper.UserName];
            foreach (var items in CartCookie.Values)
            {
                string cookieValue = CartCookie[items.ToString()].ToString();
                var product = objProductBO.GetProduct(Convert.ToInt32(items));
                objOrder.FKProductId = product.PKProductId;
                objOrder.FKBillingAddressId = addressId;
                objOrder.Status = "Processing";
                objOrder.CustomerComment = cookieValue.Split('^')[2];
                objOrderBO.InsertOrder(objOrder);
                objOrderDetail.FKProductId = product.PKProductId;
                objOrderDetail.FKOrderId = objOrder.PKOrderId;
                objOrderDetail.Cost = Convert.ToDecimal(cookieValue.Split('^')[1]);
                objOrderDetail.Quantity = Convert.ToInt32(cookieValue.Split('^')[0]);
                objOrderDetailBO.InsertOrderDetail(objOrderDetail);
                objOrderHistory.FKOrderId = objOrder.PKOrderId;
                objOrderHistory.Status = objOrder.Status;
                objOrderHistoryBO.InsertOrderHistory(objOrderHistory);
            }
            CartCookie.Expires = DateTime.Now.AddDays(-1);
            Response.Cookies.Add(CartCookie);
            return RedirectToAction("GetOrderDetails", "MyOrder");
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStoreMVCUsingLinq.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        //
        // GET: /ShowCart
        HttpCookie CartCookie;
        public ActionResult AddToCart(int? productId=0, decimal? price=0, int? quantity=0)
        {
            if (productId != 0)
            {
                CartCookie = Request.Cookies[Helper.UserName];
                if (CartCookie == null)
                {
                    CartCookie = new HttpCookie(Helper.UserName);
                    CartCookie.Expires = DateTime.MaxValue;
                }
                quantity = 1;
                CartCookie.Values[productId.ToString()] = quantity.ToString() + '^' + price.ToString();
                Response.Cookies.Add(CartCookie);
            }
            return RedirectToAction("ShowCart");
        }
        public ActionResult GetShowCartDetails(int id, int total, int qty, string customerComment)
         {
            CartCookie = Request.Cookies[Helper.UserName];
            CartCookie.Values[id.ToString()] = qty.ToString() + '^' + total.ToString() + '^' + customerComment;
            Response.Cookies.Add(CartCookie);
            return RedirectToAction("ShowCart");
        }
        public ActionResult ShowCart()
        {
            return View();
        }
        public ActionResult ShowCartProductRemove(int deleteId)
        {
            ViewBag.Id = Helper.UserId;
            HttpCookie CartCookie = Request.Cookies[Helper.UserName];
            CartCookie.Values.Remove(deleteId.ToString());
            Response.Cookies.Add(CartCookie);
            return RedirectToAction("ShowCart");
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Views/ShoppingCart/ShowCart.cshtml
@model OnlineShoppingStoreMVCUsingLinq.Product
@using OnlineShoppingStoreMVCUsingLinq.BO
@{ProductBO objProductBO = new ProductBO();}
@{
    ViewBag.Title = "ShowCart";
    Layout = "~/Views/Shared/UserLayout.cshtml";
    int availableProducts = 0;
    int availableQuantity = 0;
}

<h2>ShowCart</h2>
@using (Html.BeginForm())
{
    HttpCookie CartCookie = Request.Cookies[Helper.UserName];
    <table class="table table-bordered table-responsive">
        <tr>
            <th>ProductId</th>
            <th>ProductName</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Totalprice</th>
            <th>CustomerComment</th>

        </tr>
        @if (CartCookie != null)
        {
            foreach (var item in CartCookie.Values)
            {
                Product product = objProductBO.GetProduct(Convert.ToInt32(item));
                if (product != null)
                {
                    availableProducts = product.PKProductId;
                    availableQuantity = product.Quantity;
                    string cookieValue = CartCookie[item.ToString()].ToString();
                    <tr>
                        <td>@(product.PKProductId)</td>
                        <td>@(product.ProductName)</td>
                        <td><input type="text" name="txtQuantity" id="Quantity" value="@cookieValue.Split('^')[0]" class="quantityClass" /></td>
                        <td><input class="priceClass" type="text" name="txtPrice" id="Price" value="@product.Price" readonly="readonly" /></td>
                        <td><input class="total" type="text" name="txtTotal" value="@cookieValue.Split('^')[1]" /></td>
                        <td><input type="text" name="txtCustomerComment" class="CustomerComment" /></td>
                        <td>
                            <a href="@Url.Action("ShowCartProductRemove", "ShoppingCart", new { deleteId = product.PKProductId })">
                                delete
                            </a>
                        </td>
                    </tr>
                }
            }
        }
    </table>
    <br />
    <a href="@Url.Action("Index", "Home")">ContinueShopping </a>
    if (availableProducts != 0)
    {
        <a href="@Url.Action("PlaceOrder", "Confirm")"><input type="button" value="ConfirmOrder" name="btnConfirmOrder" class="btn-primary" /></a>
    }
}


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.quantityClass').change(function (e) {
                var id = "@availableProducts";
                var availableqty = "@availableQuantity"
                var qty = $(this).val();
                var price = $(this).parent().next().find(".priceClass").val();
                if (qty <= availableqty) {
                    var total = qty * price;
                    $(this).parent().nextAll().find(".total").val(total);
                    var customerComment = $(this).parent().nextAll().find(".CustomerComment").val();

                    $.ajax({
                        url: "GetShowCartDetails",
                        data: { id: id, total: total, qty: qty, customerComment: customerComment },
                        type: 'Get',
                    }).success(function (data) {

                    })
                }
                else {
                    alert("Available quantity is: " + availableqty);
                }
            });

        });
        $(document).ready(function () {
            $(".CustomerComment").change(function (e) {
                var id = "@availableProducts";
                var qty = $(this).parent().prevAll().find(".quantityClass").val();
                var price = $(this).parent().prevAll().find(".priceClass").val();
                var total = qty * price;
                var customerComment = $(this).val();
                $.ajax({
                    url: "GetShowCartDetails",
                    data: { id: id, total: total, qty: qty, customerComment: customerComment },
                    type: 'Get',
                }).success(function (data) {

                })
            });

        });

    </script>
}