OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStoreMVCUsingLinq;
using OnlineShoppingStoreMVCUsingLinq.BO;

namespace OnlineShoppingStoreMVCUsingLinq.Areas.Admin.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        ProductBO objProductBO = new ProductBO();
        CategoryBO objCategoryBO = new CategoryBO();
        SubCategoryBO objSubCategoryBO = new SubCategoryBO();
        ProductImageBO objProductImageBO = new ProductImageBO();

        // GET: /Admin/Product/
        public ActionResult Index()
        {
            ViewBag.Category = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            ViewBag.SubCategory = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName");
            return View(objProductBO.GetProducts());
        }
        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            if (fc["btnSearch"] == "Search")
            {
                int category = 0;
                int subCategory = 0;
                if (fc["Category"] != "")
                    category = Convert.ToInt32(fc["Category"]);
                if (fc["SubCategory"] != "")
                    subCategory = Convert.ToInt32(fc["SubCategory"]);
                ViewBag.Category = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName", category);
                ViewBag.SubCategory = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName", subCategory);
                return View(objProductBO.GetProducts(category, subCategory));
            }
            else
            {
                ViewBag.Category = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
                ViewBag.SubCategory = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName");
                return View(objProductBO.GetProducts());
            }
        }
        // GET: /Admin/Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = objProductBO.GetProduct(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        public ActionResult GetSubCategories(int id = 0)
        {
            var lstSubCategories = objSubCategoryBO.GetSubCategories(id);
            return Json(lstSubCategories, JsonRequestBehavior.AllowGet);
        }

        // GET: /Admin/Product/Create
        public ActionResult Create()
        {
            ViewBag.FKCategoryId = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            ViewBag.FKSubCategoryId = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName");
            return View();
        }

        // POST: /Admin/Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, IEnumerable<HttpPostedFileBase> images)
        {
            ProductImage objProductImage = new ProductImage();
            if (ModelState.IsValid)
            {
                objProductBO.InsertProduct(product);
                foreach (HttpPostedFileBase img in images)
                {
                    string imageName = System.IO.Path.GetFileName(img.FileName);
                    img.SaveAs(Server.MapPath("~/Images/" + imageName));
                    objProductImage.FKProductId = product.PKProductId;
                    objProductImage.ImageName = imageName;
                    objProductImage.ImagePath = "/Images/" + imageName;
                    objProductImageBO.InsertImage(objProductImage);
                }
                return RedirectToAction("Index");
            }

            ViewBag.FKCategoryId = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            ViewBag.FKSubCategoryId = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName");
            return View(product);
        }

        // GET: /Admin/Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = objProductBO.GetProduct(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.FKCategoryId = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName", product.FKCategoryId);
            ViewBag.FKSubCategoryId = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName", product.FKSubCategoryId);
            return View(product);
        }

        // POST: /Admin/Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                objProductBO.UpdateProduct(product);
                if (fc["btnEdit"] == "Edit product images")
                {
                    return RedirectToAction("Index", "Productimage", new { id = product.PKProductId });
                }
                return RedirectToAction("Index");
            }
            ViewBag.FKCategoryId = new SelectList(objCategoryBO.GetCategories(true), "PKCategoryId", "CategoryName");
            ViewBag.FKSubCategoryId = new SelectList(objSubCategoryBO.GetSubCategories(0, true), "PKSubCategoryId", "SubCategoryName");
            return View(product);
        }

        // GET: /Admin/Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = objProductBO.GetProduct(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Admin/Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<ProductImage> lstProductImage = objProductImageBO.GetImages(id);
            foreach (ProductImage p in lstProductImage)
            {
                objProductImageBO.DeleteImage(p.PKImageId);
            }
            objProductBO.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Controllers/ProductImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStoreMVCUsingLinq;
using OnlineShoppingStoreMVCUsingLinq.BO;

namespace OnlineShoppingStoreMVCUsingLinq.Areas.Admin.Controllers
{
    [Authorize]
    public class ProductImageController : Controller
    {

        ProductImageBO objProductImageBO = new ProductImageBO();
        // GET: /Admin/ProductImage/
        public ActionResult Index(int? id)
        {
            TempData["productId"] = id.Value;
            TempData.Keep();
            return View(objProductImageBO.GetImages(id.Value));
        }

        // GET: /Admin/ProductImage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/ProductImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductImage productimage, IEnumerable<HttpPostedFileBase> images)
        {
            if (ModelState.IsValid)
            {
                foreach (HttpPostedFileBase img in images)
                {
                    string imageName = System.IO.Path.GetFileName(img.FileName);
                    img.SaveAs(Server.MapPath("~/Images/" + imageName));
                    productimage.FKProductId = (int)TempData["productId"];
                    productimage.ImageName = imageName;
                    productimage.ImagePath = "/Images/" + imageName;
                    objProductImageBO.InsertImage(productimage);
                }
                return RedirectToAction("Index", new {id=productimage.FKProductId });
            }
            return View(productimage);
        }

        // GET: /Admin/ProductImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductImage productimage = objProductImageBO.GetImage(id.Value);
            if (productimage == null)
            {
                return HttpNotFound();
            }
            return View(productimage);
        }

        // POST: /Admin/ProductImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductImage productimage,HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                string imageName = System.IO.Path.GetFileName(image.FileName);
                image.SaveAs(Server.MapPath("~/Images/" + imageName));
                productimage.ImageName = imageName;
                productimage.ImagePath = "/Images/" + imageName;
                objProductImageBO.UpdateImage(productimage);
            }
            return RedirectToAction("Index", new { id = productimage.FKProductId });
        }

        // GET: /Admin/ProductImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductImage productimage = objProductImageBO.GetImage(id.Value);
            if (productimage == null)
            {
                return HttpNotFound();
            }
            return View(productimage);
        }

        // POST: /Admin/ProductImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            objProductImageBO.DeleteImage(id);
            int productId = Convert.ToInt32(TempData["productId"]);
            return RedirectToAction("Index", new { id = productId });
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/ProductImage/Create.cshtml
@model OnlineShoppingStoreMVCUsingLinq.ProductImage

@{
    ViewBag.Title = "Create";
}

<h2>Add product Images</h2>

@using (Html.BeginForm("Create", "ProductImage", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductImage</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <input type="file" name="images" value="" multiple="multiple" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/ProductImage/Delete.cshtml
@model OnlineShoppingStoreMVCUsingLinq.ProductImage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id=Model.FKProductId})
        </div>
    }
</div>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/ProductImage/Edit.cshtml
@model OnlineShoppingStoreMVCUsingLinq.ProductImage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ProductImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductImage</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.PKImageId)
        @Html.HiddenFor(model=>model.FKProductId)


        <img src="@Model.ImagePath" alt="loading...." style="max-height:150px;max-width:120px" />
       <input type="file" name="image" value="" />  
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id=Model.FKProductId})
</div>

OnlineShoppingStoreMVCUsingLinq/Areas/Admin/Views/ProductImage/Index.cshtml
@model IEnumerable<OnlineShoppingStoreMVCUsingLinq.ProductImage>

@{
    ViewBag.Title = "Index";
}

<h2>Product Images</h2>

<p>
    @Html.ActionLink("Add Product Image", "Create")
</p>
<table class="table">
    <tr>
      
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
      
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductName)
        </td>
        <td>
            <img src="@item.ImagePath" alt="loading...." style="max-height:150px;max-width:120px"/>
            <br/>
            <p>@item.ImageName.Split('.')[0].ToString()</p>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PKImageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PKImageId })
        </td>
    </tr>
}

</table>
<p>
@Html.ActionLink("Back to List", "Index", "Product")
</p>