OnlineShoppingStoreMVCUsingLinq/Controllers/CatelogController.cs
using OnlineShoppingStoreMVCUsingLinq.BO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStoreMVCUsingLinq.Controllers
{
    public class CatelogController : Controller
    {
        SubCategoryBO objSubCategoryBO = new SubCategoryBO();
        ProductBO objProductBO = new ProductBO();
        ProductImageBO objProductImageBO = new ProductImageBO();
        //
        // GET: /Catelog/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetSubCategory(int categoryId,string categoryName)
        {
            ViewBag.CategoryName = categoryName;
            ViewBag.CategoryId = categoryId;
            return View(objSubCategoryBO.GetSubCategories(categoryId));
        }
        public ActionResult GetProducts(int categoryId,string categoryName,int subCategoryId,string subCategoryName)
        {
            ViewBag.CategoryName = categoryName;
            ViewBag.CategoryId = categoryId;
            ViewBag.SubCategoryName = subCategoryName;
            ViewBag.SubCategoryId = subCategoryId;
            return View(objProductBO.GetProducts(categoryId,subCategoryId));
        }
        public ActionResult GetProductImages(int productId)
        {
            ViewBag.ProductId = productId;
            return View(objProductImageBO.GetImages(productId));
        }
        public ActionResult GetProductDetails(int productId,string imagePath)
        {
            ViewBag.ProductId = productId;
            ViewBag.Imagepath = imagePath;
            return View(objProductBO.GetProduct(productId));
        }
	}
}

OnlineShoppingStoreMVCUsingLinq/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStoreMVCUsingLinq.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        //
        // GET: /ShowCart
        HttpCookie CartCookie;
        public ActionResult AddToCart(int? productId=0, decimal? price=0, int? quantity=0)
        {
            if (productId != 0)
            {
                CartCookie = Request.Cookies[Helper.UserName];
                if (CartCookie == null)
                {
                    CartCookie = new HttpCookie(Helper.UserName);
                    CartCookie.Expires = DateTime.MaxValue;
                }
                quantity = 1;
                CartCookie.Values[productId.ToString()] = quantity.ToString() + '^' + price.ToString();
                Response.Cookies.Add(CartCookie);
            }
            return RedirectToAction("ShowCart");
        }
        public ActionResult GetShowCartDetails(int id, int total, int qty, string customerComment)
         {
            CartCookie = Request.Cookies[Helper.UserName];
            CartCookie.Values[id.ToString()] = qty.ToString() + '^' + total.ToString() + '^' + customerComment;
            Response.Cookies.Add(CartCookie);
            return RedirectToAction("ShowCart");
        }
        public ActionResult ShowCart()
        {
            return View();
        }
        public ActionResult ShowCartProductRemove(int deleteId)
        {
            ViewBag.Id = Helper.UserId;
            HttpCookie CartCookie = Request.Cookies[Helper.UserName];
            CartCookie.Values.Remove(deleteId.ToString());
            Response.Cookies.Add(CartCookie);
            return RedirectToAction("ShowCart");
        }
    }
}

OnlineShoppingStoreMVCUsingLinq/Views/Catelog/GetProductDetails.cshtml
@model OnlineShoppingStoreMVCUsingLinq.Product
@{
    ViewBag.Title = "ProductDetails";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<h3>Product Details</h3>
<div class="row">
    <div class="col-md-4">
        <img class="Zoom" style="height:250px;width:250px" src=@ViewBag.ImagePath alt="Loading.." data-zoom-image="@ViewBag.ImagePath" />
    </div>
    <div class="col-md-6">
        <h4>Product Name: @Html.DisplayFor(model => model.ProductName)</h4><br />
        <h4>Description:@Html.DisplayFor(model => model.Description)</h4><br />
        <h4>Price:</h4><h4 style="font-family:cursive;color:red">@Html.DisplayFor(model => model.Price)</h4>
    </div>
</div>

<p style="padding-left:10%"><a href="@Url.Action("AddToCart", "ShoppingCart", new {productId=@Model.PKProductId,price=@Model.Price,quantity=@Model.Quantity })"><input type="submit" value="BuyNow" name="btnBuyNow" class="btn-primary" /></a></p>
@section Scripts{
<script src="~/Scripts/jquery.elevatezoom.js"></script> 
     <script type="text/javascript">
        $(".Zoom").elevateZoom();
    </script>
}

OnlineShoppingStoreMVCUsingLinq/Views/Catelog/GetProductImages.cshtml
@model IEnumerable<OnlineShoppingStoreMVCUsingLinq.ProductImage>
@{
    ViewBag.Title = "ProductImages";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<h3></h3>
<div class="container">
    @foreach (var items in Model)
    {
        <div class="col-sm-3 img-responsive">
            <a href=@Url.Action("GetProductDetails", "Catelog", new { productId = @items.FKProductId,imagePath=@items.ImagePath})>
                <center>
                    <img src="@items.ImagePath" alt="Loading.." style="max-height:180px"/>
                    <p>@items.ImageName.Split('.')[0].ToString()</p>
                </center> 
            </a>
        </div>
    }

</div>

OnlineShoppingStoreMVCUsingLinq/Views/Catelog/GetProducts.cshtml
@model IEnumerable<OnlineShoppingStoreMVCUsingLinq.Product>
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div  style="font-weight:bold;font-size:18px;margin:0px 0px 0px 15px">@ViewBag.subCategoryName</div>
<div class="container">
    @foreach (var items in Model)
    {
        <div class="col-sm-3 img-responsive">
        <a href=@Url.Action("GetProductImages", "Catelog", new {productId=@items.PKProductId })><center><img src="@items.ImagePath" alt="Loading.." style="max-height:150px" /><br/> @items.ImageName.Split('.')[0].ToString()</center></a>
           
        </div>
    }
</div>

OnlineShoppingStoreMVCUsingLinq/Views/Catelog/GetSubCategory.cshtml
@model  IEnumerable<OnlineShoppingStoreMVCUsingLinq.SubCategory>
@{
    ViewBag.Title = "SubCategory";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div style="font-weight:bold;font-size:18px;margin:0px 0px 0px 15px">@ViewBag.CategoryName</div>
<div class="container">
    @foreach (var items in Model)
    {
        <div class="col-xs-3 img-responsive">
            <a href="@Url.Action("GetProducts", "Catelog", new { categoryId = @items.FKCategoryId, categoryName = @items.CategoryName, subCategoryId = @items.PKSubCategoryId, subCategoryName = @items.SubCategoryName })"><img src="@items.ImagePath" alt="Loading..... " height="150" width="150"/></a>
            <p>@items.ImageName.Split('.')[0].ToString()</p>
        </div>
    }
</div>